package com.soltini.app.orchestrator

import org.json.JSONArray
import org.json.JSONObject

enum class IntentType {
    CONVERSATIONAL,      // Pure chit-chat, reasoning, or informational answer
    ACTIONABLE,          // Requires executing one or more plugins/tools/APIs
    MULTISTEP_COMPLEX,   // Requires chaining multiple steps with conditional logic
    EXPLICIT_MEMORY,     // Explicit user instruction to remember something
    MEMORY_QUERY,        // User asking what MYRA remembers or asking to view memory
    MEMORY_DELETE,       // User asking to delete a specific memory
    MEMORY_UPDATE,       // User asking to update an existing memory
    USER_CORRECTION      // User correcting MYRA's previous behavior or providing a preference rule
}

enum class PlanStatus {
    CREATED,
    PLANNING,
    EXECUTING,
    COMPLETED,
    FAILED,
    PARTIALLY_COMPLETED
}

/**
 * OrchestratorPlan
 *
 * Generated by MYRA Orchestrator after understanding intent and consulting Memory 2.0 & Plugin Registry.
 */
data class OrchestratorPlan(
    val id: String = java.util.UUID.randomUUID().toString(),
    val userGoal: String,
    val intentType: IntentType,
    val steps: MutableList<TaskStep> = mutableListOf(),
    var status: PlanStatus = PlanStatus.CREATED,
    var finalResponse: String = "",
    val createdAt: Long = System.currentTimeMillis()
) {
    fun toJsonObject(): JSONObject = JSONObject().apply {
        put("id", id)
        put("user_goal", userGoal)
        put("intent_type", intentType.name)
        put("status", status.name)
        val arr = JSONArray()
        steps.forEach { arr.put(it.toJsonObject()) }
        put("steps", arr)
        put("final_response", finalResponse)
    }
}

/**
 * OrchestratorResult
 *
 * Final consolidated output returned by MYRA Orchestrator.
 */
data class OrchestratorResult(
    val plan: OrchestratorPlan,
    val isSuccess: Boolean,
    val responseText: String,
    val toolSequenceUsed: List<String> = emptyList(),
    val memoryUpdated: Boolean = false,
    val executionDurationMs: Long = 0L
)
