package com.soltini.app.memory

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import android.util.Log
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import java.util.UUID
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * UnifiedMemory
 *
 * Represents an atomic unit of permanent knowledge, user profile attribute,
 * preference, active reminder, or relationship fact.
 */
data class UnifiedMemory(
    val id: String = UUID.randomUUID().toString(),
    val category: String = "FACT", // FACT, PREFERENCE, REMINDER, PERSON, PROJECT, HABIT, NOTE
    val keyName: String = "",
    val content: String,
    val importance: Float = 0.8f, // 0.0 to 1.0 (0.9+ = critical fact / identity)
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val lastRecalledAt: Long = System.currentTimeMillis(),
    val recallCount: Int = 0,
    val userConfirmed: Boolean = true,
    val tags: List<String> = emptyList()
)

data class PastConversationRecap(
    val sessionId: String = UUID.randomUUID().toString(),
    val startedAt: Long = System.currentTimeMillis(),
    val endedAt: Long = System.currentTimeMillis(),
    val summary: String,
    val keyPoints: List<String> = emptyList()
)

data class ConversationTurn(
    val id: String = UUID.randomUUID().toString(),
    val sender: String, // USER or MYRA
    val text: String,
    val timestamp: Long = System.currentTimeMillis()
)

data class DiaryEntry(
    val id: String = UUID.randomUUID().toString(),
    val title: String,
    val content: String,
    val dateMillis: Long = System.currentTimeMillis(),
    val dateString: String = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date()),
    val mood: String = "NEUTRAL",
    val category: String = "NOTE",
    val tags: List<String> = emptyList(),
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * MyraUnifiedMemory
 *
 * Single, reliable, unified persistent memory engine for Myra.
 * Features:
 *   1. 100% offline, local SQLite storage that survives app restarts, task kills, and reboots.
 *   2. Native Hindi, Hinglish, and English intelligent fact & preference extraction.
 *   3. Smart deduplication and update resolution (e.g. updating name or phone instead of duplicating).
 *   4. Past conversation recaps and session topic tracking so Myra always remembers what was discussed.
 *   5. Comprehensive context prompt formatting for Gemini Live and Myra Orchestrator.
 *   6. First-class tool support for voice interactions (save_memory, recall_memories, get_past_conversations, forget_memory).
 */
class MyraUnifiedMemory private constructor(context: Context) : SQLiteOpenHelper(
    context.applicationContext, DB_NAME, null, DB_VERSION
) {
    companion object {
        private const val TAG = "MyraUnifiedMemory"
        private const val DB_NAME = "myra_unified_memory.db"
        private const val DB_VERSION = 3

        private const val TABLE_MEMORIES = "unified_memories"
        private const val TABLE_SESSIONS = "conversation_sessions"
        private const val TABLE_TURNS = "conversation_turns"
        private const val TABLE_SCHEDULED_TASKS = "scheduled_tasks"
        private const val TABLE_DIARY = "daily_diary"

        @Volatile
        private var instance: MyraUnifiedMemory? = null

        fun getInstance(context: Context): MyraUnifiedMemory =
            instance ?: synchronized(this) {
                instance ?: MyraUnifiedMemory(context.applicationContext).also {
                    instance = it
                    CoroutineScope(Dispatchers.IO).launch {
                        it.ensureDeveloperProfileSeeded()
                    }
                }
            }
    }

    override fun onCreate(db: SQLiteDatabase) {
        // 1. Unified Memories Table
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS $TABLE_MEMORIES (
                id TEXT PRIMARY KEY,
                category TEXT NOT NULL,
                key_name TEXT,
                content TEXT NOT NULL,
                importance REAL DEFAULT 0.7,
                created_at INTEGER NOT NULL,
                updated_at INTEGER NOT NULL,
                last_recalled_at INTEGER NOT NULL,
                recall_count INTEGER DEFAULT 0,
                user_confirmed INTEGER DEFAULT 1,
                tags TEXT
            )
        """.trimIndent())

        // Index for fast search
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_mem_category ON $TABLE_MEMORIES(category)")
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_mem_importance ON $TABLE_MEMORIES(importance DESC)")

        // 2. Past Conversation Sessions (Summaries & topics)
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS $TABLE_SESSIONS (
                session_id TEXT PRIMARY KEY,
                started_at INTEGER NOT NULL,
                ended_at INTEGER NOT NULL,
                summary TEXT NOT NULL,
                key_points TEXT
            )
        """.trimIndent())

        // 3. Conversation Turns
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS $TABLE_TURNS (
                id TEXT PRIMARY KEY,
                sender TEXT NOT NULL,
                text TEXT NOT NULL,
                timestamp INTEGER NOT NULL
            )
        """.trimIndent())
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_turn_time ON $TABLE_TURNS(timestamp DESC)")

        // 4. Scheduled Tasks (Maintained for ScheduledTaskManager compatibility)
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS $TABLE_SCHEDULED_TASKS (
                id TEXT PRIMARY KEY,
                task_type TEXT NOT NULL,
                title TEXT NOT NULL,
                command TEXT NOT NULL,
                parsed_intent TEXT,
                parameters_json TEXT,
                scheduled_at INTEGER NOT NULL,
                timezone TEXT,
                recurrence_rule TEXT,
                status TEXT NOT NULL,
                requires_confirmation INTEGER DEFAULT 0,
                created_at INTEGER,
                updated_at INTEGER,
                last_executed_at INTEGER,
                next_execution_at INTEGER,
                retry_count INTEGER DEFAULT 0,
                max_retries INTEGER DEFAULT 3,
                execution_notes TEXT,
                geofence_id TEXT,
                geofence_transition TEXT
            )
        """.trimIndent())

        // 5. Daily Diary & Notes Table
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS $TABLE_DIARY (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                content TEXT NOT NULL,
                date_millis INTEGER NOT NULL,
                date_string TEXT NOT NULL,
                mood TEXT DEFAULT 'NEUTRAL',
                category TEXT DEFAULT 'NOTE',
                tags TEXT,
                is_auto_generated INTEGER DEFAULT 0,
                created_at INTEGER NOT NULL
            )
        """.trimIndent())
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_diary_date ON $TABLE_DIARY(date_string)")
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_diary_time ON $TABLE_DIARY(date_millis DESC)")
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        if (oldVersion < 3) {
            db.execSQL("""
                CREATE TABLE IF NOT EXISTS $TABLE_DIARY (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    content TEXT NOT NULL,
                    date_millis INTEGER NOT NULL,
                    date_string TEXT NOT NULL,
                    mood TEXT DEFAULT 'NEUTRAL',
                    category TEXT DEFAULT 'NOTE',
                    tags TEXT,
                    is_auto_generated INTEGER DEFAULT 0,
                    created_at INTEGER NOT NULL
                )
            """.trimIndent())
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_diary_date ON $TABLE_DIARY(date_string)")
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_diary_time ON $TABLE_DIARY(date_millis DESC)")
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // MEMORY MANAGEMENT (CRUD + DEDUPLICATION)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Saves a memory item with automatic deduplication.
     * If an existing memory has similar key or content, updates it.
     */
    fun saveMemory(
        content: String,
        category: String = "FACT",
        importance: Float = 0.8f,
        tags: List<String> = emptyList(),
        keyName: String? = null
    ): UnifiedMemory {
        val trimmed = content.trim()
        if (trimmed.isBlank()) {
            return UnifiedMemory(content = "")
        }

        val normalizedCategory = category.uppercase(Locale.ROOT).trim().ifBlank { "FACT" }
        val derivedKey = (keyName ?: deriveKey(trimmed, normalizedCategory)).lowercase(Locale.ROOT).trim()

        val autoTags = (tags + extractSearchTokens(trimmed) + listOf(normalizedCategory.lowercase(Locale.ROOT)))
            .distinct()
            .filter { it.isNotBlank() }

        val db = writableDatabase
        val now = System.currentTimeMillis()

        // Check if an existing memory matches this key or has high overlap
        val existing = findExistingMemory(derivedKey, trimmed)
        val targetId = existing?.id ?: UUID.randomUUID().toString()
        val finalImportance = if (existing != null) maxOf(existing.importance, importance) else importance

        val cv = ContentValues().apply {
            put("id", targetId)
            put("category", normalizedCategory)
            put("key_name", derivedKey)
            put("content", trimmed)
            put("importance", finalImportance)
            put("updated_at", now)
            put("last_recalled_at", now)
            put("user_confirmed", 1)
            put("tags", autoTags.joinToString(","))
            if (existing == null) {
                put("created_at", now)
                put("recall_count", 0)
            }
        }

        if (existing != null) {
            db.update(TABLE_MEMORIES, cv, "id = ?", arrayOf(targetId))
            Log.i(TAG, "Updated existing memory [$targetId]: $trimmed")
        } else {
            db.insertWithOnConflict(TABLE_MEMORIES, null, cv, SQLiteDatabase.CONFLICT_REPLACE)
            Log.i(TAG, "Inserted new memory [$targetId]: $trimmed")
        }

        return UnifiedMemory(
            id = targetId,
            category = normalizedCategory,
            keyName = derivedKey,
            content = trimmed,
            importance = finalImportance,
            createdAt = existing?.createdAt ?: now,
            updatedAt = now,
            lastRecalledAt = now,
            recallCount = (existing?.recallCount ?: 0) + 1,
            userConfirmed = true,
            tags = autoTags
        )
    }

    private fun findExistingMemory(key: String, content: String): UnifiedMemory? {
        val db = readableDatabase

        // 1. Check exact key match for unique profile items (e.g. user_name, birthday)
        if (key.isNotBlank() && key != "general_fact") {
            db.query(
                TABLE_MEMORIES,
                null,
                "key_name = ?",
                arrayOf(key),
                null, null, null, "1"
            ).use { cursor ->
                if (cursor.moveToFirst()) return cursorToMemory(cursor)
            }
        }

        // 2. Check exact content match
        db.query(
            TABLE_MEMORIES,
            null,
            "content = ?",
            arrayOf(content),
            null, null, null, "1"
        ).use { cursor ->
            if (cursor.moveToFirst()) return cursorToMemory(cursor)
        }

        // 3. Substring / high-overlap check for short statements
        if (content.length > 8) {
            val prefix = content.take(30)
            db.query(
                TABLE_MEMORIES,
                null,
                "content LIKE ?",
                arrayOf("%$prefix%"),
                null, null, null, "1"
            ).use { cursor ->
                if (cursor.moveToFirst()) return cursorToMemory(cursor)
            }
        }

        return null
    }

    fun getAllMemories(): List<UnifiedMemory> {
        val list = mutableListOf<UnifiedMemory>()
        val db = readableDatabase
        db.query(
            TABLE_MEMORIES,
            null,
            null,
            null,
            null,
            null,
            "importance DESC, updated_at DESC"
        ).use { cursor ->
            while (cursor.moveToNext()) {
                list.add(cursorToMemory(cursor))
            }
        }
        return list
    }

    fun searchMemories(query: String, limit: Int = 10): List<UnifiedMemory> {
        val trimmed = query.trim()
        if (trimmed.isBlank()) return getAllMemories().take(limit)

        val tokens = extractSearchTokens(trimmed)
        val all = getAllMemories()

        // Score based on token matches, key matches, importance, and recency
        return all.map { memory ->
            var score = 0f
            val lowerContent = memory.content.lowercase(Locale.ROOT)
            val lowerKey = memory.keyName.lowercase(Locale.ROOT)
            val lowerCategory = memory.category.lowercase(Locale.ROOT)

            if (lowerContent.contains(trimmed.lowercase(Locale.ROOT))) {
                score += 50f
            }
            if (lowerKey.contains(trimmed.lowercase(Locale.ROOT))) {
                score += 30f
            }

            for (token in tokens) {
                if (lowerContent.contains(token)) score += 10f
                if (lowerKey.contains(token)) score += 15f
                if (lowerCategory.contains(token)) score += 5f
                if (memory.tags.any { it.contains(token, ignoreCase = true) }) score += 8f
            }

            score += memory.importance * 10f
            Pair(memory, score)
        }
            .filter { it.second > 0f }
            .sortedByDescending { it.second }
            .take(limit)
            .map { it.first }
    }

    fun deleteMemory(id: String): Boolean {
        val db = writableDatabase
        val rows = db.delete(TABLE_MEMORIES, "id = ?", arrayOf(id))
        return rows > 0
    }

    fun deleteMemoriesMatching(query: String): Int {
        val matches = searchMemories(query, limit = 50)
        var count = 0
        for (m in matches) {
            if (deleteMemory(m.id)) count++
        }
        return count
    }

    fun clearAllMemories(): Boolean {
        val db = writableDatabase
        db.delete(TABLE_MEMORIES, null, null)
        db.delete(TABLE_TURNS, null, null)
        db.delete(TABLE_SESSIONS, null, null)
        return true
    }

    fun updateMemory(id: String, newContent: String, newCategory: String? = null): Boolean {
        val db = writableDatabase
        val cv = ContentValues().apply {
            put("content", newContent.trim())
            if (!newCategory.isNullOrBlank()) {
                put("category", newCategory.uppercase(Locale.ROOT).trim())
            }
            put("updated_at", System.currentTimeMillis())
        }
        return db.update(TABLE_MEMORIES, cv, "id = ?", arrayOf(id)) > 0
    }

    // ─────────────────────────────────────────────────────────────────────────
    // CONVERSATION SESSIONS & PAST TOPIC TRACKING
    // ─────────────────────────────────────────────────────────────────────────

    fun recordTurn(sender: String, text: String, id: String = UUID.randomUUID().toString()) {
        val trimmed = text.trim()
        if (trimmed.isBlank()) return

        val db = writableDatabase
        val cv = ContentValues().apply {
            put("id", id)
            put("sender", sender)
            put("text", trimmed)
            put("timestamp", System.currentTimeMillis())
        }
        db.insertWithOnConflict(TABLE_TURNS, null, cv, SQLiteDatabase.CONFLICT_REPLACE)
    }

    fun getRecentTurns(limit: Int = 30): List<ConversationTurn> {
        val list = mutableListOf<ConversationTurn>()
        val db = readableDatabase
        db.query(
            TABLE_TURNS,
            null,
            null,
            null,
            null,
            null,
            "timestamp DESC",
            limit.toString()
        ).use { cursor ->
            while (cursor.moveToNext()) {
                list.add(
                    ConversationTurn(
                        id = cursor.getString(cursor.getColumnIndexOrThrow("id")),
                        sender = cursor.getString(cursor.getColumnIndexOrThrow("sender")),
                        text = cursor.getString(cursor.getColumnIndexOrThrow("text")),
                        timestamp = cursor.getLong(cursor.getColumnIndexOrThrow("timestamp"))
                    )
                )
            }
        }
        return list.reversed()
    }

    fun recordSessionSummary(
        summary: String,
        keyPoints: List<String> = emptyList(),
        startedAt: Long = System.currentTimeMillis(),
        endedAt: Long = System.currentTimeMillis()
    ) {
        val trimmed = summary.trim()
        if (trimmed.isBlank()) return

        val db = writableDatabase
        val cv = ContentValues().apply {
            put("session_id", UUID.randomUUID().toString())
            put("started_at", startedAt)
            put("ended_at", endedAt)
            put("summary", trimmed)
            put("key_points", keyPoints.joinToString(" || "))
        }
        db.insert(TABLE_SESSIONS, null, cv)
        Log.i(TAG, "Recorded session summary: $trimmed")
    }

    fun getRecentSessionSummaries(limit: Int = 5): List<PastConversationRecap> {
        val list = mutableListOf<PastConversationRecap>()
        val db = readableDatabase
        db.query(
            TABLE_SESSIONS,
            null,
            null,
            null,
            null,
            null,
            "ended_at DESC",
            limit.toString()
        ).use { cursor ->
            while (cursor.moveToNext()) {
                val kpRaw = cursor.getString(cursor.getColumnIndexOrThrow("key_points")) ?: ""
                val points = if (kpRaw.isNotBlank()) kpRaw.split(" || ") else emptyList()
                list.add(
                    PastConversationRecap(
                        sessionId = cursor.getString(cursor.getColumnIndexOrThrow("session_id")),
                        startedAt = cursor.getLong(cursor.getColumnIndexOrThrow("started_at")),
                        endedAt = cursor.getLong(cursor.getColumnIndexOrThrow("ended_at")),
                        summary = cursor.getString(cursor.getColumnIndexOrThrow("summary")),
                        keyPoints = points
                    )
                )
            }
        }
        return list
    }

    /**
     * Automatically reviews recent conversation turns and creates a session summary if needed.
     */
    fun autoSummarizeSessionIfDue() {
        val turns = getRecentTurns(limit = 20)
        if (turns.size < 4) return // Not enough conversation to summarize

        val userTurns = turns.filter { it.sender == "USER" }.map { it.text }
        val agentTurns = turns.filter { it.sender == "MYRA" || it.sender == "GEMINI" }.map { it.text }

        if (userTurns.isEmpty()) return

        val mainTopics = userTurns.takeLast(4).joinToString("; ")
        val summary = "Discussed: $mainTopics"
        val firstTime = turns.first().timestamp
        val lastTime = turns.last().timestamp

        recordSessionSummary(
            summary = summary,
            keyPoints = userTurns.takeLast(3),
            startedAt = firstTime,
            endedAt = lastTime
        )
    }

    // ─────────────────────────────────────────────────────────────────────────
    // MULTI-LINGUAL FACT EXTRACTION (HINDI / HINGLISH / ENGLISH)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Extracts persistent facts from spoken or typed statements in Hindi, Hinglish, or English.
     */
    fun extractFactsFromText(text: String, isUser: Boolean = true): List<UnifiedMemory> {
        val cleaned = text.trim()
        if (cleaned.length < 4) return emptyList()

        val lower = cleaned.lowercase(Locale.ROOT)
        val extracted = mutableListOf<UnifiedMemory>()

        // 1. User Name Extraction
        // "mera naam rahul hai", "my name is rahul", "mujhe rahul bulao", "call me rahul"
        val nameRegexes = listOf(
            Regex("(?i)(?:mera naam|my name is|naam hai|call me|mujhe bulao)\\s+([a-zA-Z\\u0900-\\u097F]+)"),
            Regex("(?i)main\\s+([a-zA-Z\\u0900-\\u097F]+)\\s+hoon")
        )
        for (rx in nameRegexes) {
            rx.find(cleaned)?.let { match ->
                val name = match.groupValues[1].trim()
                if (name.length in 2..20 && !name.equals("hai", true) && !name.equals("hoon", true)) {
                    val mem = saveMemory(
                        content = "User ka naam $name hai.",
                        category = "PERSON",
                        importance = 1.0f,
                        keyName = "user_name"
                    )
                    extracted.add(mem)
                }
            }
        }

        // 2. Explicit "Remember that" / "Yaad rakhna" statements
        // "yaad rakhna kal exam hai", "remember that i hate spicy food"
        val rememberRegex = Regex("(?i)(?:yaad rakhna ki|yaad rakhna|yaad rakh|remember that|remember to|keep in mind that|hamesha yaad rakhna)\\s+(.+)")
        rememberRegex.find(cleaned)?.let { match ->
            val fact = match.groupValues[1].trim()
            if (fact.length > 3) {
                val category = if (fact.contains("kal", true) || fact.contains("tomorrow", true) || fact.contains("baje", true)) "REMINDER" else "FACT"
                val mem = saveMemory(
                    content = fact,
                    category = category,
                    importance = 0.95f,
                    keyName = "explicit_user_rule"
                )
                extracted.add(mem)
            }
        }

        // 3. User Preferences (Likes & Dislikes)
        // "mujhe coffee pasand hai", "i like dark chocolate", "meri favorite movie interstellar hai"
        if (lower.contains("pasand hai") || lower.contains("pasand nahi") || lower.contains("favorite") || lower.contains("i like") || lower.contains("i love") || lower.contains("i prefer")) {
            val mem = saveMemory(
                content = cleaned,
                category = "PREFERENCE",
                importance = 0.85f,
                keyName = "user_preference"
            )
            extracted.add(mem)
        }

        // 4. Family & Friends (Relationships)
        // "mera bhai rohit", "my friend sneha", "meri mummy ka naam"
        val relationKeywords = listOf("bhai", "sister", "dost", "friend", "mother", "father", "mummy", "papa", "wife", "husband", "brother")
        if (relationKeywords.any { lower.contains(it) }) {
            val mem = saveMemory(
                content = cleaned,
                category = "PERSON",
                importance = 0.85f,
                keyName = "family_and_friends"
            )
            extracted.add(mem)
        }

        // 5. Important Reminders & Upcoming Plans
        // "kal subah 8 baje uthna hai", "tomorrow is my interview", "somwar ko doctor ke paas jana hai"
        val reminderKeywords = listOf("kal", "tomorrow", "exam", "interview", "meeting", "flight", "train", "baje", "doctor", "medicine", "subah", "shaam")
        if (reminderKeywords.any { lower.contains(it) } && (lower.contains("hai") || lower.contains("jana") || lower.contains("karna") || lower.contains("have to") || lower.contains("need to"))) {
            val mem = saveMemory(
                content = cleaned,
                category = "REMINDER",
                importance = 0.90f,
                keyName = "active_plan"
            )
            extracted.add(mem)
        }

        return extracted
    }

    // ─────────────────────────────────────────────────────────────────────────
    // CONTEXT PROMPT BUILDER FOR GEMINI LIVE & MYRA ORCHESTRATOR
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Builds a comprehensive Markdown block injected directly into Myra's system instruction.
     * Contains:
     *   - User identity & core facts
     *   - Preferences & habits
     *   - Active reminders & upcoming plans
     *   - Past conversation recaps & previous topics discussed
     *   - Clear instructions on how Myra should reference previous talks and use memory tools.
     */
    fun buildSystemPromptContext(): String {
        val memories = getAllMemories()
        val recaps = getRecentSessionSummaries(limit = 4)
        val recentTurns = getRecentTurns(limit = 10)

        val sb = StringBuilder()
        sb.append("\n\n### 🧠 MYRA'S ACTIVE PERMANENT MEMORY & PAST CONVERSATION HISTORY:\n")

        // 1. Facts & Profile
        val facts = memories.filter { it.category == "PERSON" || it.category == "FACT" || it.category == "PROJECT" }
        if (facts.isNotEmpty()) {
            sb.append("\n[USER IDENTITY & KNOWN FACTS]:\n")
            for (f in facts.take(8)) {
                sb.append("• ${f.content}\n")
            }
        }

        // 2. Preferences
        val prefs = memories.filter { it.category == "PREFERENCE" || it.category == "HABIT" }
        if (prefs.isNotEmpty()) {
            sb.append("\n[USER PREFERENCES & HABITS]:\n")
            for (p in prefs.take(6)) {
                sb.append("• ${p.content}\n")
            }
        }

        // 3. Active Reminders & Important Topics
        val reminders = memories.filter { it.category == "REMINDER" || it.category == "NOTE" }
        if (reminders.isNotEmpty()) {
            sb.append("\n[ACTIVE REMINDERS & IMPORTANT UPCOMING TOPICS]:\n")
            for (r in reminders.take(6)) {
                sb.append("• ⏰ ${r.content}\n")
            }
        }

        // 4. Past Conversation Recaps (What we discussed previously)
        if (recaps.isNotEmpty()) {
            val sdf = SimpleDateFormat("dd MMM, hh:mm a", Locale.getDefault())
            sb.append("\n[PURANI BAATEIN / RECENT PAST CONVERSATIONS DISCUSSED]:\n")
            for (recap in recaps) {
                val timeStr = sdf.format(Date(recap.endedAt))
                sb.append("• ($timeStr): ${recap.summary}\n")
            }
        } else if (recentTurns.isNotEmpty()) {
            sb.append("\n[LAST CONVERSATION EXCERPTS]:\n")
            for (turn in recentTurns.takeLast(6)) {
                sb.append("• ${turn.sender}: ${turn.text.take(60)}\n")
            }
        }

        // 5. Daily Diary & Notes
        val diaryEntries = getAllDiaryEntries().take(5)
        if (diaryEntries.isNotEmpty()) {
            sb.append("\n[USER'S DIARY & PERMANENT DAILY NOTES]:\n")
            for (d in diaryEntries) {
                sb.append("• [${d.dateString} - ${d.title}]: ${d.content.take(140)}\n")
            }
        }

        // 6. Memory & Diary Behavioral Rules
        sb.append("""

### 📌 CRITICAL MEMORY & DIARY DIRECTIVES:
1. You have a FULL, PERMANENT MEMORY across all past and present conversations and diary notes. You NEVER say "I have no memory" or "I cannot remember".
2. If the user asks "humari purani baat kis pr hui thi?", "humne pehle kya baat ki thi?", "kya yaad hai?", or refers to earlier chats: ALWAYS reference the past conversations and topics listed above warmly and accurately in Hindi/Hinglish!
3. If the user asks about their diary or notes ("meri diary sunao", "aaj ki diary me kya hai?"): recite the relevant entries from [USER'S DIARY & PERMANENT DAILY NOTES] or call `read_diary`.
4. If the user tells you to write in their diary or note something down ("diary me likho...", "note karlo diary me...", "aaj ye hua diary me likh do"): IMMEDIATELY call `save_diary_note` and confirm with warmth!
5. If the user mentions ANY new detail, personal fact, brother/sister/friend, exam, plan, preference, or asks "yaad rakhna": IMMEDIATELY call the `save_memory` tool so it is permanently preserved!
6. If you need more specific details about past discussions, you can call `recall_memories` or `get_past_conversations`.
7. If the user asks you to forget or remove something, call `forget_memory`.
""")

        return sb.toString()
    }

    // ─────────────────────────────────────────────────────────────────────────
    // HELPERS & INTERNAL PARSING
    // ─────────────────────────────────────────────────────────────────────────

    private fun deriveKey(content: String, category: String): String {
        val lower = content.lowercase(Locale.ROOT)
        return when {
            lower.contains("naam") || lower.contains("name") -> "user_name"
            lower.contains("bhai") || lower.contains("brother") -> "user_brother"
            lower.contains("dost") || lower.contains("friend") -> "user_friend"
            lower.contains("pasand") || lower.contains("like") || lower.contains("favorite") -> "user_preference"
            lower.contains("exam") || lower.contains("interview") -> "user_exam"
            lower.contains("birthday") || lower.contains("janmdin") -> "user_birthday"
            lower.contains("kal") || lower.contains("tomorrow") -> "upcoming_schedule"
            else -> "${category.lowercase(Locale.ROOT)}_${UUID.randomUUID().toString().take(6)}"
        }
    }

    private fun extractSearchTokens(text: String): List<String> {
        val stopWords = setOf("hai", "ki", "ka", "ke", "ko", "mai", "main", "mera", "meri", "mere", "the", "a", "an", "is", "in", "to", "and", "or", "of", "for", "with", "ye", "wo")
        return text.lowercase(Locale.ROOT)
            .split(" ", ",", ".", "?", "!", ":", ";", "\n", "\t", "-", "_")
            .map { it.trim() }
            .filter { it.length > 2 && !stopWords.contains(it) }
            .distinct()
    }

    private fun cursorToMemory(cursor: android.database.Cursor): UnifiedMemory {
        val tagsRaw = cursor.getString(cursor.getColumnIndexOrThrow("tags")) ?: ""
        val tags = if (tagsRaw.isNotBlank()) tagsRaw.split(",") else emptyList()
        return UnifiedMemory(
            id = cursor.getString(cursor.getColumnIndexOrThrow("id")),
            category = cursor.getString(cursor.getColumnIndexOrThrow("category")),
            keyName = cursor.getString(cursor.getColumnIndexOrThrow("key_name")) ?: "",
            content = cursor.getString(cursor.getColumnIndexOrThrow("content")),
            importance = cursor.getFloat(cursor.getColumnIndexOrThrow("importance")),
            createdAt = cursor.getLong(cursor.getColumnIndexOrThrow("created_at")),
            updatedAt = cursor.getLong(cursor.getColumnIndexOrThrow("updated_at")),
            lastRecalledAt = cursor.getLong(cursor.getColumnIndexOrThrow("last_recalled_at")),
            recallCount = cursor.getInt(cursor.getColumnIndexOrThrow("recall_count")),
            userConfirmed = cursor.getInt(cursor.getColumnIndexOrThrow("user_confirmed")) == 1,
            tags = tags
        )
    }

    // ─────────────────────────────────────────────────────────────────────────
    // DAILY MEMORY DIARY & NOTES CRUD
    // ─────────────────────────────────────────────────────────────────────────

    fun saveDiaryEntry(
        title: String,
        content: String,
        mood: String = "NEUTRAL",
        category: String = "NOTE",
        tags: List<String> = emptyList(),
        isAutoGenerated: Boolean = false,
        dateMillis: Long = System.currentTimeMillis()
    ): DiaryEntry {
        val db = writableDatabase
        val id = UUID.randomUUID().toString()
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val dateString = sdf.format(Date(dateMillis))

        val cv = ContentValues().apply {
            put("id", id)
            put("title", title.trim())
            put("content", content.trim())
            put("date_millis", dateMillis)
            put("date_string", dateString)
            put("mood", mood.uppercase(Locale.ROOT))
            put("category", category.uppercase(Locale.ROOT))
            put("tags", tags.joinToString(","))
            put("is_auto_generated", if (isAutoGenerated) 1 else 0)
            put("created_at", System.currentTimeMillis())
        }
        db.insertWithOnConflict(TABLE_DIARY, null, cv, SQLiteDatabase.CONFLICT_REPLACE)

        return DiaryEntry(
            id = id,
            title = title.trim(),
            content = content.trim(),
            dateMillis = dateMillis,
            dateString = dateString,
            mood = mood.uppercase(Locale.ROOT),
            category = category.uppercase(Locale.ROOT),
            tags = tags,
            isAutoGenerated = isAutoGenerated,
            createdAt = System.currentTimeMillis()
        )
    }

    fun getAllDiaryEntries(): List<DiaryEntry> {
        val db = readableDatabase
        val list = mutableListOf<DiaryEntry>()
        val cursor = db.rawQuery(
            "SELECT * FROM $TABLE_DIARY ORDER BY date_millis DESC, created_at DESC",
            null
        )
        cursor.use {
            while (it.moveToNext()) {
                list.add(cursorToDiaryEntry(it))
            }
        }
        return list
    }

    fun getDiaryEntriesForDate(dateString: String): List<DiaryEntry> {
        val db = readableDatabase
        val list = mutableListOf<DiaryEntry>()
        val cursor = db.rawQuery(
            "SELECT * FROM $TABLE_DIARY WHERE date_string = ? ORDER BY created_at DESC",
            arrayOf(dateString)
        )
        cursor.use {
            while (it.moveToNext()) {
                list.add(cursorToDiaryEntry(it))
            }
        }
        return list
    }

    fun deleteDiaryEntry(id: String): Boolean {
        val db = writableDatabase
        return db.delete(TABLE_DIARY, "id = ?", arrayOf(id)) > 0
    }

    fun updateDiaryEntry(
        id: String,
        newTitle: String,
        newContent: String,
        newMood: String = "NEUTRAL",
        newCategory: String = "NOTE"
    ): Boolean {
        val db = writableDatabase
        val cv = ContentValues().apply {
            put("title", newTitle.trim())
            put("content", newContent.trim())
            put("mood", newMood.uppercase(Locale.ROOT))
            put("category", newCategory.uppercase(Locale.ROOT))
        }
        return db.update(TABLE_DIARY, cv, "id = ?", arrayOf(id)) > 0
    }

    fun searchDiary(query: String): List<DiaryEntry> {
        val q = query.trim()
        if (q.isBlank()) return getAllDiaryEntries()
        val db = readableDatabase
        val list = mutableListOf<DiaryEntry>()
        val cursor = db.rawQuery(
            "SELECT * FROM $TABLE_DIARY WHERE title LIKE ? OR content LIKE ? OR tags LIKE ? ORDER BY date_millis DESC",
            arrayOf("%$q%", "%$q%", "%$q%")
        )
        cursor.use {
            while (it.moveToNext()) {
                list.add(cursorToDiaryEntry(it))
            }
        }
        return list
    }

    fun generateDailyRecapSummary(): DiaryEntry? {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val todayStr = sdf.format(Date())
        val todayStart = Calendar.getInstance().apply {
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }.timeInMillis

        // Get turns from today
        val db = readableDatabase
        val turnsToday = mutableListOf<ConversationTurn>()
        val turnCursor = db.rawQuery(
            "SELECT * FROM $TABLE_TURNS WHERE timestamp >= ? ORDER BY timestamp ASC",
            arrayOf(todayStart.toString())
        )
        turnCursor.use {
            while (it.moveToNext()) {
                turnsToday.add(
                    ConversationTurn(
                        id = it.getString(it.getColumnIndexOrThrow("id")),
                        sender = it.getString(it.getColumnIndexOrThrow("sender")),
                        text = it.getString(it.getColumnIndexOrThrow("text")),
                        timestamp = it.getLong(it.getColumnIndexOrThrow("timestamp"))
                    )
                )
            }
        }

        if (turnsToday.isEmpty()) return null

        // Get memories added today
        val memoriesToday = getAllMemories().filter { it.createdAt >= todayStart }

        val sb = StringBuilder()
        sb.append("Aaj ki baatein aur mukhya charcha:\n")
        val userMessages = turnsToday.filter { it.sender == "USER" }.map { it.text.take(80) }.distinct()
        userMessages.take(6).forEach { msg ->
            sb.append("• $msg\n")
        }

        if (memoriesToday.isNotEmpty()) {
            sb.append("\nNaye facts aur preferences jo yaad rakhe:\n")
            memoriesToday.take(5).forEach { m ->
                sb.append("• ${m.content}\n")
            }
        }

        val displayDate = SimpleDateFormat("dd MMMM yyyy", Locale.getDefault()).format(Date())
        val title = "Daily Reflection - $displayDate"

        val existingToday = getDiaryEntriesForDate(todayStr).firstOrNull { it.isAutoGenerated }
        return if (existingToday != null) {
            updateDiaryEntry(existingToday.id, title, sb.toString().trim(), "PRODUCTIVE", "DAILY_SUMMARY")
            existingToday.copy(title = title, content = sb.toString().trim(), mood = "PRODUCTIVE")
        } else {
            saveDiaryEntry(
                title = title,
                content = sb.toString().trim(),
                mood = "PRODUCTIVE",
                category = "DAILY_SUMMARY",
                isAutoGenerated = true
            )
        }
    }

    private fun cursorToDiaryEntry(cursor: android.database.Cursor): DiaryEntry {
        val tagsRaw = cursor.getString(cursor.getColumnIndexOrThrow("tags")) ?: ""
        val tags = if (tagsRaw.isNotBlank()) tagsRaw.split(",") else emptyList()
        return DiaryEntry(
            id = cursor.getString(cursor.getColumnIndexOrThrow("id")),
            title = cursor.getString(cursor.getColumnIndexOrThrow("title")),
            content = cursor.getString(cursor.getColumnIndexOrThrow("content")),
            dateMillis = cursor.getLong(cursor.getColumnIndexOrThrow("date_millis")),
            dateString = cursor.getString(cursor.getColumnIndexOrThrow("date_string")),
            mood = cursor.getString(cursor.getColumnIndexOrThrow("mood")) ?: "NEUTRAL",
            category = cursor.getString(cursor.getColumnIndexOrThrow("category")) ?: "NOTE",
            tags = tags,
            isAutoGenerated = cursor.getInt(cursor.getColumnIndexOrThrow("is_auto_generated")) == 1,
            createdAt = cursor.getLong(cursor.getColumnIndexOrThrow("created_at"))
        )
    }

    fun ensureDeveloperProfileSeeded() {
        try {
            saveMemory(
                content = "Harshit Raahi is the creator and developer of Myra. From Uttar Pradesh, India. Friendly, direct, practical, comfortable being addressed as 'bhai' or 'boss'.",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "creator", "harshit_raahi", "identity"),
                keyName = "developer_harshit_raahi"
            )
            saveMemory(
                content = "Harshit is pursuing a Diploma in Electrical Engineering at Mahamaya Polytechnic of Information Technology, Aligarh (Session 2024-2027, timing 10 AM-5 PM).",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "education", "polytechnic", "aligarh"),
                keyName = "developer_education"
            )
            saveMemory(
                content = "Harshit's academic goals: Diploma/Polytechnic examinations, JEE / IIT, RRB JE Electrical, SSC JE, UPPCL JE. Prefers Hindi notes, simple explanations, diagrams, formulas, MCQs, PYQs.",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "goals", "exams", "rrb_je", "uppcl_je"),
                keyName = "developer_goals"
            )
            saveMemory(
                content = "Harshit's tech stack: Python, C++, Java, Kotlin, Native Android development, Git/GitHub, AI/LLMs, Voice AI, ESP32 DevKit V1, L298N, DC gear motors, HC-SR04 ultrasonic, servo motors, robotic arms, relays, smart-home IoT.",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "tech", "robotics", "esp32", "ai"),
                keyName = "developer_tech"
            )
            saveMemory(
                content = "Harshit develops directly from Android (Termux, Pydroid, VS Code mobile, GitHub Actions). Never assume a PC is available; always provide mobile-compatible solutions.",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "environment", "mobile", "termux"),
                keyName = "developer_environment"
            )
            saveMemory(
                content = "Harshit's vision: Building a JARVIS-style assistant combining Electrical Engineering + Programming + AI + Robotics + Embedded Systems + Android + Automation.",
                category = "CREATOR",
                importance = 1.0f,
                tags = listOf("developer", "vision", "jarvis", "robotics"),
                keyName = "developer_vision"
            )
        } catch (e: Exception) {
            Log.e(TAG, "Error seeding developer profile: ${e.message}", e)
        }
    }
}
